import {updateCss} from './common';

export const background = {
    attachment: {
        fixed: updateCss("backgroundAttachment", "fixed"),
        inherit: updateCss("backgroundAttachment", "inherit"),
        initial: updateCss("backgroundAttachment", "initial"),
        local: updateCss("backgroundAttachment", "local"),
        scroll: updateCss("backgroundAttachment", "scroll"),
    },
    blendMode: {
        color: updateCss("backgroundBlendMode", "color"),
        colorDodge: updateCss("backgroundBlendMode", "color-dodge"),
        darken: updateCss("backgroundBlendMode", "darken"),
        lighten: updateCss("backgroundBlendMode", "lighten"),
        luminosity: updateCss("backgroundBlendMode", "luminosity"),
        multiply: updateCss("backgroundBlendMode", "multiply"),
        normal: updateCss("backgroundBlendMode", "normal"),
        overlay: updateCss("backgroundBlendMode", "overlay"),
        saturation: updateCss("backgroundBlendMode", "saturation"),
        screen: updateCss("backgroundBlendMode", "screen"),
    },
    clip: {
        borderBox: updateCss("backgroundClip", "border-box"),
        contentBox: updateCss("backgroundClip", "content-box"),
        inherit: updateCss("backgroundClip", "inherit"),
        initial: updateCss("backgroundClip", "initial"),
        paddingBox: updateCss("backgroundClip", "padding-box"),
    },
    color: {
        hex: (color:string) => updateCss("backgroundColor", `#${color}`),
        hsl: (h:number, s:number, l:number) => updateCss("backgroundColor", `rgb(${h}, ${s}%, ${l}%)`),
        hsla: (h:number, s:number, l:number, a:number) => updateCss("backgroundColor", `rgb(${h}, ${s}%, ${l}%, ${a})`),
        inherit: updateCss("backgroundColor", "inherit"),
        initial: updateCss("backgroundColor", "initial"),
        rgb: (r:number, g:number, b:number) => updateCss("backgroundColor", `rgb(${r}, ${g}, ${b})`),
        rgba: (r:number, g:number, b:number, a:number) => updateCss("backgroundColor", `rgb(${r}, ${g}, ${b}, ${a})`),
        transparent: updateCss("backgroundColor", "transparent"),
        AliceBlue: updateCss("backgroundColor","AliceBlue"),
        AntiqueWhite: updateCss("backgroundColor","AntiqueWhite"),
        Aqua: updateCss("backgroundColor","Aqua"),
        Aquamarine: updateCss("backgroundColor","Aquamarine"),
        Azure: updateCss("backgroundColor","Azure"),
        Beige: updateCss("backgroundColor","Beige"),
        Bisque: updateCss("backgroundColor","Bisque"),
        Black: updateCss("backgroundColor","Black"),
        BlanchedAlmond: updateCss("backgroundColor","BlanchedAlmond"),
        Blue: updateCss("backgroundColor","Blue"),
        BlueViolet: updateCss("backgroundColor","BlueViolet"),
        Brown: updateCss("backgroundColor","Brown"),
        BurlyWood: updateCss("backgroundColor","BurlyWood"),
        CadetBlue: updateCss("backgroundColor","CadetBlue"),
        Chartreuse: updateCss("backgroundColor","Chartreuse"),
        Chocolate: updateCss("backgroundColor","Chocolate"),
        Coral: updateCss("backgroundColor","Coral"),
        CornflowerBlue: updateCss("backgroundColor","CornflowerBlue"),
        Cornsilk: updateCss("backgroundColor","Cornsilk"),
        Crimson: updateCss("backgroundColor","Crimson"),
        Cyan: updateCss("backgroundColor","Cyan"),
        DarkBlue: updateCss("backgroundColor","DarkBlue"),
        DarkCyan: updateCss("backgroundColor","DarkCyan"),
        DarkGoldenRod: updateCss("backgroundColor","DarkGoldenRod"),
        DarkGray: updateCss("backgroundColor","DarkGray"),
        DarkGrey: updateCss("backgroundColor","DarkGrey"),
        DarkGreen: updateCss("backgroundColor","DarkGreen"),
        DarkKhaki: updateCss("backgroundColor","DarkKhaki"),
        DarkMagenta: updateCss("backgroundColor","DarkMagenta"),
        DarkOliveGreen: updateCss("backgroundColor","DarkOliveGreen"),
        DarkOrange: updateCss("backgroundColor","DarkOrange"),
        DarkOrchid: updateCss("backgroundColor","DarkOrchid"),
        DarkRed: updateCss("backgroundColor","DarkRed"),
        DarkSalmon: updateCss("backgroundColor","DarkSalmon"),
        DarkSeaGreen: updateCss("backgroundColor","DarkSeaGreen"),
        DarkSlateBlue: updateCss("backgroundColor","DarkSlateBlue"),
        DarkSlateGray: updateCss("backgroundColor","DarkSlateGray"),
        DarkSlateGrey: updateCss("backgroundColor","DarkSlateGrey"),
        DarkTurquoise: updateCss("backgroundColor","DarkTurquoise"),
        DarkViolet: updateCss("backgroundColor","DarkViolet"),
        DeepPink: updateCss("backgroundColor","DeepPink"),
        DeepSkyBlue: updateCss("backgroundColor","DeepSkyBlue"),
        DimGray: updateCss("backgroundColor","DimGray"),
        DimGrey: updateCss("backgroundColor","DimGrey"),
        DodgerBlue: updateCss("backgroundColor","DodgerBlue"),
        FireBrick: updateCss("backgroundColor","FireBrick"),
        FloralWhite: updateCss("backgroundColor","FloralWhite"),
        ForestGreen: updateCss("backgroundColor","ForestGreen"),
        Fuchsia: updateCss("backgroundColor","Fuchsia"),
        Gainsboro: updateCss("backgroundColor","Gainsboro"),
        GhostWhite: updateCss("backgroundColor","GhostWhite"),
        Gold: updateCss("backgroundColor","Gold"),
        GoldenRod: updateCss("backgroundColor","GoldenRod"),
        Gray: updateCss("backgroundColor","Gray"),
        Grey: updateCss("backgroundColor","Grey"),
        Green: updateCss("backgroundColor","Green"),
        GreenYellow: updateCss("backgroundColor","GreenYellow"),
        HoneyDew: updateCss("backgroundColor","HoneyDew"),
        HotPink: updateCss("backgroundColor","HotPink"),
        IndianRed : updateCss("backgroundColor","IndianRed "),
        Indigo : updateCss("backgroundColor","Indigo "),
        Ivory: updateCss("backgroundColor","Ivory"),
        Khaki: updateCss("backgroundColor","Khaki"),
        Lavender: updateCss("backgroundColor","Lavender"),
        LavenderBlush: updateCss("backgroundColor","LavenderBlush"),
        LawnGreen: updateCss("backgroundColor","LawnGreen"),
        LemonChiffon: updateCss("backgroundColor","LemonChiffon"),
        LightBlue: updateCss("backgroundColor","LightBlue"),
        LightCoral: updateCss("backgroundColor","LightCoral"),
        LightCyan: updateCss("backgroundColor","LightCyan"),
        LightGoldenRodYellow: updateCss("backgroundColor","LightGoldenRodYellow"),
        LightGray: updateCss("backgroundColor","LightGray"),
        LightGrey: updateCss("backgroundColor","LightGrey"),
        LightGreen: updateCss("backgroundColor","LightGreen"),
        LightPink: updateCss("backgroundColor","LightPink"),
        LightSalmon: updateCss("backgroundColor","LightSalmon"),
        LightSeaGreen: updateCss("backgroundColor","LightSeaGreen"),
        LightSkyBlue: updateCss("backgroundColor","LightSkyBlue"),
        LightSlateGray: updateCss("backgroundColor","LightSlateGray"),
        LightSlateGrey: updateCss("backgroundColor","LightSlateGrey"),
        LightSteelBlue: updateCss("backgroundColor","LightSteelBlue"),
        LightYellow: updateCss("backgroundColor","LightYellow"),
        Lime: updateCss("backgroundColor","Lime"),
        LimeGreen: updateCss("backgroundColor","LimeGreen"),
        Linen: updateCss("backgroundColor","Linen"),
        Magenta: updateCss("backgroundColor","Magenta"),
        Maroon: updateCss("backgroundColor","Maroon"),
        MediumAquaMarine: updateCss("backgroundColor","MediumAquaMarine"),
        MediumBlue: updateCss("backgroundColor","MediumBlue"),
        MediumOrchid: updateCss("backgroundColor","MediumOrchid"),
        MediumPurple: updateCss("backgroundColor","MediumPurple"),
        MediumSeaGreen: updateCss("backgroundColor","MediumSeaGreen"),
        MediumSlateBlue: updateCss("backgroundColor","MediumSlateBlue"),
        MediumSpringGreen: updateCss("backgroundColor","MediumSpringGreen"),
        MediumTurquoise: updateCss("backgroundColor","MediumTurquoise"),
        MediumVioletRed: updateCss("backgroundColor","MediumVioletRed"),
        MidnightBlue: updateCss("backgroundColor","MidnightBlue"),
        MintCream: updateCss("backgroundColor","MintCream"),
        MistyRose: updateCss("backgroundColor","MistyRose"),
        Moccasin: updateCss("backgroundColor","Moccasin"),
        NavajoWhite: updateCss("backgroundColor","NavajoWhite"),
        Navy: updateCss("backgroundColor","Navy"),
        OldLace: updateCss("backgroundColor","OldLace"),
        Olive: updateCss("backgroundColor","Olive"),
        OliveDrab: updateCss("backgroundColor","OliveDrab"),
        Orange: updateCss("backgroundColor","Orange"),
        OrangeRed: updateCss("backgroundColor","OrangeRed"),
        Orchid: updateCss("backgroundColor","Orchid"),
        PaleGoldenRod: updateCss("backgroundColor","PaleGoldenRod"),
        PaleGreen: updateCss("backgroundColor","PaleGreen"),
        PaleTurquoise: updateCss("backgroundColor","PaleTurquoise"),
        PaleVioletRed: updateCss("backgroundColor","PaleVioletRed"),
        PapayaWhip: updateCss("backgroundColor","PapayaWhip"),
        PeachPuff: updateCss("backgroundColor","PeachPuff"),
        Peru: updateCss("backgroundColor","Peru"),
        Pink: updateCss("backgroundColor","Pink"),
        Plum: updateCss("backgroundColor","Plum"),
        PowderBlue: updateCss("backgroundColor","PowderBlue"),
        Purple: updateCss("backgroundColor","Purple"),
        RebeccaPurple: updateCss("backgroundColor","RebeccaPurple"),
        Red: updateCss("backgroundColor","Red"),
        RosyBrown: updateCss("backgroundColor","RosyBrown"),
        RoyalBlue: updateCss("backgroundColor","RoyalBlue"),
        SaddleBrown: updateCss("backgroundColor","SaddleBrown"),
        Salmon: updateCss("backgroundColor","Salmon"),
        SandyBrown: updateCss("backgroundColor","SandyBrown"),
        SeaGreen: updateCss("backgroundColor","SeaGreen"),
        SeaShell: updateCss("backgroundColor","SeaShell"),
        Sienna: updateCss("backgroundColor","Sienna"),
        Silver: updateCss("backgroundColor","Silver"),
        SkyBlue: updateCss("backgroundColor","SkyBlue"),
        SlateBlue: updateCss("backgroundColor","SlateBlue"),
        SlateGray: updateCss("backgroundColor","SlateGray"),
        SlateGrey: updateCss("backgroundColor","SlateGrey"),
        Snow: updateCss("backgroundColor","Snow"),
        SpringGreen: updateCss("backgroundColor","SpringGreen"),
        SteelBlue: updateCss("backgroundColor","SteelBlue"),
        Tan: updateCss("backgroundColor","Tan"),
        Teal: updateCss("backgroundColor","Teal"),
        Thistle: updateCss("backgroundColor","Thistle"),
        Tomato: updateCss("backgroundColor","Tomato"),
        Turquoise: updateCss("backgroundColor","Turquoise"),
        Violet: updateCss("backgroundColor","Violet"),
        Wheat: updateCss("backgroundColor","Wheat"),
        White: updateCss("backgroundColor","White"),
        WhiteSmoke: updateCss("backgroundColor","WhiteSmoke"),
        Yellow: updateCss("backgroundColor","Yellow"),
        YellowGreen: updateCss("backgroundColor","YellowGreen"),
    },
    image: {
        // TODO
    },
    origin: {
        borderBox: updateCss("backgroundOrigin", "border-box"),
        contentBox: updateCss("backgroundOrigin", "content-box"),
        inherit: updateCss("backgroundOrigin", "inherit"),
        initial: updateCss("backgroundOrigin", "initial"),
        paddingBox: updateCss("backgroundOrigin", "padding-box"),
    },
    position: {
        // TODO
    },
    repeat: {
        // TODO
    },
    size: {
        // TODO
    },
}
